---
runtime: ruby
env: flex
entrypoint: bundle exec rackup -I lib --port 8080 --host 0.0.0.0 ./api/config.ru 
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cpu_utilization:
    target_utilization: 0.5
